//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_proyecto_empleado
    {
        public System.Guid idDetalleEmpleado { get; set; }
        public System.Guid idProyecto { get; set; }
        public System.Guid idEmpleado { get; set; }
        public System.DateTime fechaIngresoEmpleado { get; set; }
        public double valorGanancia { get; set; }
        public string estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
