//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_informe_material_faltante
    {
        public System.Guid idDetalleMaterialFaltante { get; set; }
        public System.Guid idInformeCompra { get; set; }
        public System.Guid idMaterialFaltante { get; set; }
    
        public virtual Informe_compra Informe_compra { get; set; }
        public virtual Material_faltante Material_faltante { get; set; }
    }
}
