//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Detalle_proyecto_empleado = new HashSet<Detalle_proyecto_empleado>();
        }
    
        public System.Guid idEmpleado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int nroDocumento { get; set; }
        public double sueldo { get; set; }
        public int cantidadProyectosActivos { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_proyecto_empleado> Detalle_proyecto_empleado { get; set; }
    }
}
