//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestorCMBEntities : DbContext
    {
        public GestorCMBEntities()
            : base("name=GestorCMBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Detalle_informe_material_faltante> Detalle_informe_material_faltante { get; set; }
        public virtual DbSet<Detalle_proyecto_empleado> Detalle_proyecto_empleado { get; set; }
        public virtual DbSet<Detalle_proyecto_material> Detalle_proyecto_material { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Informe_compra> Informe_compra { get; set; }
        public virtual DbSet<Informe_monto> Informe_monto { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Material_faltante> Material_faltante { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
    }
}
