//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class Informe_snapshot_faltante
    {
        public System.Guid idSnapshotFaltante { get; set; }
        public System.Guid idInformeCompra { get; set; }
        public string descripcionArticuloFaltante { get; set; }
        public string tipoMaterialFaltante { get; set; }
        public string tipoUnidadMaterialFaltante { get; set; }
        public int cantidadFaltante { get; set; }
    }
}
