//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_monto
    {
        public System.Guid idInformeMonto { get; set; }
        public System.Guid idProyecto { get; set; }
        public double totalMateriales { get; set; }
        public double totalEmpleados { get; set; }
        public double montoTotal { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
