//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Informe_compra()
        {
            this.Detalle_informe_material_faltante = new HashSet<Detalle_informe_material_faltante>();
        }
    
        public System.Guid idInformeCompra { get; set; }
        public System.Guid idProyecto { get; set; }
        public System.DateTime fechaRealizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_informe_material_faltante> Detalle_informe_material_faltante { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
