//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public System.Guid idMaterialInventario { get; set; }
        public int cantidad { get; set; }
        public System.Guid idMaterial { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
